export const CLINICS = [
  // ── Реальная клиника-партнёр ──────────────────────────────
  {
    id: "medgard-orenburg",
    slug: "medgard-orenburg",
    name: "Медгард Оренбург — Лечебно-диагностический комплекс",
    city: "Оренбург",
    address: "Оренбург, ул. Берег Урала, 4",
    lat: 51.7727,
    lng: 55.0988,
    phone: "+7 (3532) 50-03-03",
    email: "ldk56@medguard.ru",
    website: "https://oren.medguard.ru",
    hours: "Пн–Пт 8:00–20:00, Сб–Вс 8:00–17:00",
    price: 0,          // TODO: уточнить у Ильи цену DXA body composition
    priceLabel: "Уточняйте по телефону",  // TODO: заменить на реальную цену
    services: ["DXA body composition", "Висцеральный жир", "Костная плотность", "Денситометрия позвоночника", "Денситометрия бедра"],
    description: "Анализ состава тела на европейском денситометре Stratos dR в крупнейшей частной клинике Оренбурга. Жир, мышцы, кость, висцеральный жир — за одно исследование.",
    device: "Stratos dR (DMS Imaging)",
    rating: 4.8,
    reviews: 0,
    img: "🏥",
    partner: true,
    isPartner: true,
    network: "Медгард — сеть клиник в Поволжье (Оренбург, Самара, Тольятти, Саратов, Ульяновск, Набережные Челны, Пенза, Энгельс)",
    slots: ["08:00", "09:00", "10:00", "11:00", "13:00", "14:00", "15:00", "16:00", "17:00"],
    comingSoon: false,
  },

  // ── "Скоро в вашем городе" ────────────────────────────────
  {
    id: "medgard-samara",
    slug: "medgard-samara",
    name: "Медгард Самара",
    city: "Самара",
    address: "Самара — адрес уточняется",
    lat: 53.1959,
    lng: 50.1002,
    phone: null,
    hours: null,
    price: 0,
    priceLabel: "Скоро",
    services: ["DXA body composition"],
    device: null,
    rating: null,
    reviews: 0,
    img: "🔜",
    partner: false,
    slots: [],
    comingSoon: true,
  },
  {
    id: "coming-moscow",
    slug: "coming-moscow",
    name: "Партнёрская клиника — Москва",
    city: "Москва",
    address: "Москва — клиника подбирается",
    lat: 55.7558,
    lng: 37.6173,
    phone: null,
    hours: null,
    price: 0,
    priceLabel: "Скоро",
    services: ["DXA body composition"],
    device: null,
    rating: null,
    reviews: 0,
    img: "🔜",
    partner: false,
    slots: [],
    comingSoon: true,
  },
  {
    id: "coming-spb",
    slug: "coming-spb",
    name: "Партнёрская клиника — Санкт-Петербург",
    city: "Санкт-Петербург",
    address: "Санкт-Петербург — клиника подбирается",
    lat: 59.9343,
    lng: 30.3351,
    phone: null,
    hours: null,
    price: 0,
    priceLabel: "Скоро",
    services: ["DXA body composition"],
    device: null,
    rating: null,
    reviews: 0,
    img: "🔜",
    partner: false,
    slots: [],
    comingSoon: true,
  },
  {
    id: "coming-kazan",
    slug: "coming-kazan",
    name: "Партнёрская клиника — Казань",
    city: "Казань",
    address: "Казань — клиника подбирается",
    lat: 55.7887,
    lng: 49.1221,
    phone: null,
    hours: null,
    price: 0,
    priceLabel: "Скоро",
    services: ["DXA body composition"],
    device: null,
    rating: null,
    reviews: 0,
    img: "🔜",
    partner: false,
    slots: [],
    comingSoon: true,
  },
];

export const CITIES = ["Все города", "Оренбург", "Самара", "Москва", "Санкт-Петербург", "Казань"];
